### ISSUE TITLE
테스트셋을 공유해주실수 있나요?

### ISSUE THREAD

**Issue by galoisjung** [su-park/mteb_ko_leaderboard#1]
안녕하세요. 
일단 상세한 분석 자료 잘 봤습니다. 모델을 선택하는데 있어 한글과 영어 성능의 괴리가 꽤 있는것 같아 놀랐고 정말 큰 도움이 됐습니다.
가능하다면 테스트셋 가지고 저도 직접 성능을 테스트 해보고 싶은데 테스트셋을 공유해 주실 수 있는지 궁금합니다.

끝으로 다시 한번 공개해주신 데이터와 노고에 감사드립니다.

답변 기다리겠습니다.

**Comment by su-park** [comment]
- 안녕하세요.
- 도움이 되셨다니 다행이네요.
- 열거된 데이터들은 제가 따로 아카이빙하고 있는 자료가 아닙니다.
- 저 역시 huggingface 등을 통해 접근 가능한, 데이터 기반으로 측정을 진행하고 있습니다.
- 다소 불편하시겠지만 데이터셋명으로 검색하시면 어렵지 않게 구하실 수 있으셔서 확인드립니다.
- 관심가져주셔서 고맙습니다.
