### ISSUE TITLE
안녕하세요, 기여 하고 싶은데 혹시 어떤 방식으로 할 수 있을지 논의해볼 수 있을까요?

### ISSUE THREAD

**Issue by sigridjineth** [su-park/mteb_ko_leaderboard#3]
안녕하세요.
임베딩 리더보드 벤치마크 제작과 기여에 관심이 있습니다. 혹시 어떻게 참여해볼 수 있을까요?

**Comment by su-park** [comment]
안녕하세요.
메일로 주신 문의 글 보았습니다.

생각하고 계신 기여 방식이나 지향이 있으시다면 구체적으로 제안을 주시면 좋겠습니다.
관심가져주시고, 연락주셔서 고맙습니다.

**Comment by realsigridjin** [comment]
@su-park 안녕하십니까. 추석 등 때문에 일정이 밀려서 이메일을 워낙 늦게 회신 드렸네요 ㅎㅎ..
답신 드렸으니, 확인해주시면 감사하겠습니다!
