### ISSUE TITLE
jinaai/jina-embeddings-v3 모델도 부탁드려도 될까요?

### ISSUE THREAD

**Issue by sunkeunchoi** [su-park/mteb_ko_leaderboard#5]
Jinaai  jina-embeddings-v3 모델도 부탁드립니다.
https://huggingface.co/jinaai/jina-embeddings-v3
정리를 너무 잘해주셔서 감사합니다.

**Comment by su-park** [comment]
요청하신 결과를 게시해두었습니다.

**Comment by sunkeunchoi** [comment]
감사합니다.! 한눈에 볼 수 있어서 다시 한번 감사 드립니다.
